
pub enum Mode {
    Implied,
    Immediate,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndirectX,
    IndirectY,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Accumulator,
    Relative,
}

pub struct Opcode {
    pub code: u8,
    pub name: &'static str,
    pub mode: Mode,
    pub bytes: u8,
    pub cycles: u8,
}

pub fn get_opcode<'a>(op: u8) -> Option<&'a Opcode> {
    match OPCODES.iter().find(|o| o.code == op) {
        Some(val) => Some(val),
        None => None,
    }
}

static OPCODES: [Opcode; 151] = [Opcode {
                                     code: 0x00,
                                     name: "BRK",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 7,
                                 },
                                 Opcode {
                                     code: 0x01,
                                     name: "ORA",
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x05,
                                     name: "ORA",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0x06,
                                     name: "ASL",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0x08,
                                     name: "PHP",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0x09,
                                     name: "ORA",
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x0A,
                                     name: "ASL",
                                     mode: Mode::Accumulator,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x0D,
                                     name: "ORA",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x0E,
                                     name: "ASL",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x10,
                                     name: "BPL",
                                     mode: Mode::Relative,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x11,
                                     name: "ORA",
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0x15,
                                     name: "ORA",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x16,
                                     name: "ASL",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x18,
                                     name: "CLC",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x19,
                                     name: "ORA",
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x1D,
                                     name: "ORA",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x1E,
                                     name: "ASL",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 7,
                                 },
                                 Opcode {
                                     code: 0x20,
                                     name: "JSR",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x21,
                                     name: "AND",
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x24,
                                     name: "BIT",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0x25,
                                     name: "AND",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0x26,
                                     name: "ROL",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0x28,
                                     name: "PLP",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x29,
                                     name: "AND",
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x2A,
                                     name: "ROL",
                                     mode: Mode::Accumulator,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x2C,
                                     name: "BIT",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x2D,
                                     name: "AND",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x2E,
                                     name: "ROL",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x30,
                                     name: "BMI",
                                     mode: Mode::Relative,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x31,
                                     name: "AND",
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0x35,
                                     name: "AND",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x36,
                                     name: "ROL",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x38,
                                     name: "SEC",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x39,
                                     name: "AND",
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x3D,
                                     name: "AND",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x3E,
                                     name: "ROL",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 7,
                                 },
                                 Opcode {
                                     code: 0x40,
                                     name: "RTI",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x41,
                                     name: "EOR",
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x45,
                                     name: "EOR",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0x46,
                                     name: "LSR",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0x48,
                                     name: "PHA",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0x49,
                                     name: "EOR",
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x4A,
                                     name: "LSR",
                                     mode: Mode::Accumulator,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x4C,
                                     name: "JMP",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0x4D,
                                     name: "EOR",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x4E,
                                     name: "LSR",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x50,
                                     name: "BVC",
                                     mode: Mode::Relative,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x51,
                                     name: "EOR",
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0x55,
                                     name: "EOR",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x56,
                                     name: "LSR",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x58,
                                     name: "CLI",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x59,
                                     name: "EOR",
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x5D,
                                     name: "EOR",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x5E,
                                     name: "LSR",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 7,
                                 },
                                 Opcode {
                                     code: 0x60,
                                     name: "RTS",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x61,
                                     name: "ADC",
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x65,
                                     name: "ADC",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0x66,
                                     name: "ROR",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0x68,
                                     name: "PLA",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x69,
                                     name: "ADC",
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x6A,
                                     name: "ROR",
                                     mode: Mode::Accumulator,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x6C,
                                     name: "JMP",
                                     mode: Mode::Indirect,
                                     bytes: 3,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0x6D,
                                     name: "ADC",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x6E,
                                     name: "ROR",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x70,
                                     name: "BVS",
                                     mode: Mode::Relative,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x71,
                                     name: "ADC",
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0x75,
                                     name: "ADC",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x76,
                                     name: "ROR",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x78,
                                     name: "SEI",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x79,
                                     name: "ADC",
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x7D,
                                     name: "ADC",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x7E,
                                     name: "ROR",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 7,
                                 },
                                 Opcode {
                                     code: 0x81,
                                     name: "STA",
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x84,
                                     name: "STY",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0x85,
                                     name: "STA",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0x86,
                                     name: "STX",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0x88,
                                     name: "DEY",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x8A,
                                     name: "TXA",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x8C,
                                     name: "STY",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x8D,
                                     name: "STA",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x8E,
                                     name: "STX",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x90,
                                     name: "BCC",
                                     mode: Mode::Relative,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x91,
                                     name: "STA",
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0x94,
                                     name: "STY",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x95,
                                     name: "STA",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0x96,
                                     name: "STX",
                                     mode: Mode::ZeroPageY,
                                     bytes: 2,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0x98,
                                     name: "TYA",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x99,
                                     name: "STA",
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0x9A,
                                     name: "TXS",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0x9D,
                                     name: "STA",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0xA0,
                                     name: "LDY",
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xA1,
                                     name: "LDA",
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0xA2,
                                     name: "LDX",
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xA4,
                                     name: "LDY",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0xA5,
                                     name: "LDA",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0xA6,
                                     name: "LDX",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0xA8,
                                     name: "TAY",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xA9,
                                     name: "LDA",
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xAA,
                                     name: "TAX",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xAC,
                                     name: "LDY",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xAD,
                                     name: "LDA",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xAE,
                                     name: "LDX",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xB0,
                                     name: "BCS",
                                     mode: Mode::Relative,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xB1,
                                     name: "LDA",
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0xB4,
                                     name: "LDY",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xB5,
                                     name: "LDA",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xB6,
                                     name: "LDX",
                                     mode: Mode::ZeroPageY,
                                     bytes: 2,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xB8,
                                     name: "CLV",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xB9,
                                     name: "LDA",
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xBA,
                                     name: "TSX",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xBC,
                                     name: "LDY",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xBD,
                                     name: "LDA",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xBE,
                                     name: "LDX",
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xC0,
                                     name: "CPY",
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xC1,
                                     name: "CMP",
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0xC4,
                                     name: "CPY",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0xC5,
                                     name: "CMP",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0xC6,
                                     name: "DEC",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0xC8,
                                     name: "INY",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xC9,
                                     name: "CMP",
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xCA,
                                     name: "DEX",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xCC,
                                     name: "CPY",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xCD,
                                     name: "CMP",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xCE,
                                     name: "DEC",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0xD0,
                                     name: "BNE",
                                     mode: Mode::Relative,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xD1,
                                     name: "CMP",
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0xD5,
                                     name: "CMP",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xD6,
                                     name: "DEC",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0xD8,
                                     name: "CLD",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xD9,
                                     name: "CMP",
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xDD,
                                     name: "CMP",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xDE,
                                     name: "DEC",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 7,
                                 },
                                 Opcode {
                                     code: 0xE0,
                                     name: "CPX",
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xE1,
                                     name: "SBC",
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0xE4,
                                     name: "CPX",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0xE5,
                                     name: "SBC",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 3,
                                 },
                                 Opcode {
                                     code: 0xE6,
                                     name: "INC",
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0xE8,
                                     name: "INX",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xE9,
                                     name: "SBC",
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xEA,
                                     name: "NOP",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xEC,
                                     name: "CPX",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xED,
                                     name: "SBC",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xEE,
                                     name: "INC",
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0xF0,
                                     name: "BEQ",
                                     mode: Mode::Relative,
                                     bytes: 2,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xF1,
                                     name: "SBC",
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                     cycles: 5,
                                 },
                                 Opcode {
                                     code: 0xF5,
                                     name: "SBC",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xF6,
                                     name: "INC",
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                     cycles: 6,
                                 },
                                 Opcode {
                                     code: 0xF8,
                                     name: "SED",
                                     mode: Mode::Implied,
                                     bytes: 1,
                                     cycles: 2,
                                 },
                                 Opcode {
                                     code: 0xF9,
                                     name: "SBC",
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xFD,
                                     name: "SBC",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 4,
                                 },
                                 Opcode {
                                     code: 0xFE,
                                     name: "INC",
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                     cycles: 7,
                                 }];

#[cfg(test)]
mod tests {
    use opcodes::*;

    #[test]
    fn known_opcode_should_be_found() {
        match get_opcode(0x00) {
            Some(_v) => {}
            None => assert!(false),
        }
    }

    #[test]
    fn unknown_opcode_should_not_be_found() {
        match get_opcode(0xFF) {
            Some(_v) => assert!(false),
            None => {}
        }
    }
}
